<?php

namespace AppBundle\Repository;

/**
 * PlanelModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanelModelRepository extends \Doctrine\ORM\EntityRepository
{
}
